//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.27 at 06:01:09 PM IST 
//


package com.dxc.paws.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PolicyDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolicyDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="regionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="policyStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="companyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="faceAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lifeOrAnnuity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fixedOrVariable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="blockIndicator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalPurchasePremium" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="participantNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="groupNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="governmentIndicator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="insuredSSN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="insuredFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="insuredMiddleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="insuredLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="insuredBirthDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="insuredEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="insuredPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="insuredAddressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="insuredAddressLine2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="insuredAddressLine3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="insuredAddressLine4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="insuredCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="insuredStateCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="insuredZipCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ownerOrganizationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ownerFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ownerMiddleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ownerLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ownerSSN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="agentNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="agentFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="agentLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolicyDetail", propOrder = {
    "regionCode",
    "policyStatus",
    "companyCode",
    "productCode",
    "faceAmount",
    "lifeOrAnnuity",
    "fixedOrVariable",
    "blockIndicator",
    "totalPurchasePremium",
    "participantNumber",
    "groupNumber",
    "governmentIndicator",
    "insuredSSN",
    "insuredFirstName",
    "insuredMiddleName",
    "insuredLastName",
    "insuredBirthDate",
    "insuredEmail",
    "insuredPhone",
    "insuredAddressLine1",
    "insuredAddressLine2",
    "insuredAddressLine3",
    "insuredAddressLine4",
    "insuredCity",
    "insuredStateCode",
    "insuredZipCode",
    "ownerOrganizationName",
    "ownerFirstName",
    "ownerMiddleName",
    "ownerLastName",
    "ownerSSN",
    "agentNumber",
    "agentFirstName",
    "agentLastName"
})
public class PolicyDetail {

    @XmlElement(required = true)
    protected String regionCode;
    @XmlElement(required = true)
    protected String policyStatus;
    @XmlElement(required = true)
    protected String companyCode;
    @XmlElement(required = true)
    protected String productCode;
    @XmlElement(required = true)
    protected String faceAmount;
    @XmlElement(required = true)
    protected String lifeOrAnnuity;
    @XmlElement(required = true)
    protected String fixedOrVariable;
    @XmlElement(required = true)
    protected String blockIndicator;
    @XmlElement(required = true)
    protected String totalPurchasePremium;
    @XmlElement(required = true)
    protected String participantNumber;
    @XmlElement(required = true)
    protected String groupNumber;
    @XmlElement(required = true)
    protected String governmentIndicator;
    @XmlElement(required = true)
    protected String insuredSSN;
    @XmlElement(required = true)
    protected String insuredFirstName;
    @XmlElement(required = true)
    protected String insuredMiddleName;
    @XmlElement(required = true)
    protected String insuredLastName;
    @XmlElement(required = true)
    protected String insuredBirthDate;
    @XmlElement(required = true)
    protected String insuredEmail;
    @XmlElement(required = true)
    protected String insuredPhone;
    @XmlElement(required = true)
    protected String insuredAddressLine1;
    @XmlElement(required = true)
    protected String insuredAddressLine2;
    @XmlElement(required = true)
    protected String insuredAddressLine3;
    @XmlElement(required = true)
    protected String insuredAddressLine4;
    @XmlElement(required = true)
    protected String insuredCity;
    @XmlElement(required = true)
    protected String insuredStateCode;
    @XmlElement(required = true)
    protected String insuredZipCode;
    @XmlElement(required = true)
    protected String ownerOrganizationName;
    @XmlElement(required = true)
    protected String ownerFirstName;
    @XmlElement(required = true)
    protected String ownerMiddleName;
    @XmlElement(required = true)
    protected String ownerLastName;
    @XmlElement(required = true)
    protected String ownerSSN;
    @XmlElement(required = true)
    protected String agentNumber;
    @XmlElement(required = true)
    protected String agentFirstName;
    @XmlElement(required = true)
    protected String agentLastName;

    /**
     * Gets the value of the regionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * Sets the value of the regionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionCode(String value) {
        this.regionCode = value;
    }

    /**
     * Gets the value of the policyStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyStatus() {
        return policyStatus;
    }

    /**
     * Sets the value of the policyStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyStatus(String value) {
        this.policyStatus = value;
    }

    /**
     * Gets the value of the companyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * Sets the value of the companyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyCode(String value) {
        this.companyCode = value;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the faceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaceAmount() {
        return faceAmount;
    }

    /**
     * Sets the value of the faceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaceAmount(String value) {
        this.faceAmount = value;
    }

    /**
     * Gets the value of the lifeOrAnnuity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLifeOrAnnuity() {
        return lifeOrAnnuity;
    }

    /**
     * Sets the value of the lifeOrAnnuity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLifeOrAnnuity(String value) {
        this.lifeOrAnnuity = value;
    }

    /**
     * Gets the value of the fixedOrVariable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixedOrVariable() {
        return fixedOrVariable;
    }

    /**
     * Sets the value of the fixedOrVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixedOrVariable(String value) {
        this.fixedOrVariable = value;
    }

    /**
     * Gets the value of the blockIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockIndicator() {
        return blockIndicator;
    }

    /**
     * Sets the value of the blockIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockIndicator(String value) {
        this.blockIndicator = value;
    }

    /**
     * Gets the value of the totalPurchasePremium property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalPurchasePremium() {
        return totalPurchasePremium;
    }

    /**
     * Sets the value of the totalPurchasePremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalPurchasePremium(String value) {
        this.totalPurchasePremium = value;
    }

    /**
     * Gets the value of the participantNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParticipantNumber() {
        return participantNumber;
    }

    /**
     * Sets the value of the participantNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParticipantNumber(String value) {
        this.participantNumber = value;
    }

    /**
     * Gets the value of the groupNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupNumber() {
        return groupNumber;
    }

    /**
     * Sets the value of the groupNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupNumber(String value) {
        this.groupNumber = value;
    }

    /**
     * Gets the value of the governmentIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGovernmentIndicator() {
        return governmentIndicator;
    }

    /**
     * Sets the value of the governmentIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGovernmentIndicator(String value) {
        this.governmentIndicator = value;
    }

    /**
     * Gets the value of the insuredSSN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredSSN() {
        return insuredSSN;
    }

    /**
     * Sets the value of the insuredSSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredSSN(String value) {
        this.insuredSSN = value;
    }

    /**
     * Gets the value of the insuredFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredFirstName() {
        return insuredFirstName;
    }

    /**
     * Sets the value of the insuredFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredFirstName(String value) {
        this.insuredFirstName = value;
    }

    /**
     * Gets the value of the insuredMiddleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredMiddleName() {
        return insuredMiddleName;
    }

    /**
     * Sets the value of the insuredMiddleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredMiddleName(String value) {
        this.insuredMiddleName = value;
    }

    /**
     * Gets the value of the insuredLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredLastName() {
        return insuredLastName;
    }

    /**
     * Sets the value of the insuredLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredLastName(String value) {
        this.insuredLastName = value;
    }

    /**
     * Gets the value of the insuredBirthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredBirthDate() {
        return insuredBirthDate;
    }

    /**
     * Sets the value of the insuredBirthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredBirthDate(String value) {
        this.insuredBirthDate = value;
    }

    /**
     * Gets the value of the insuredEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredEmail() {
        return insuredEmail;
    }

    /**
     * Sets the value of the insuredEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredEmail(String value) {
        this.insuredEmail = value;
    }

    /**
     * Gets the value of the insuredPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredPhone() {
        return insuredPhone;
    }

    /**
     * Sets the value of the insuredPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredPhone(String value) {
        this.insuredPhone = value;
    }

    /**
     * Gets the value of the insuredAddressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredAddressLine1() {
        return insuredAddressLine1;
    }

    /**
     * Sets the value of the insuredAddressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredAddressLine1(String value) {
        this.insuredAddressLine1 = value;
    }

    /**
     * Gets the value of the insuredAddressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredAddressLine2() {
        return insuredAddressLine2;
    }

    /**
     * Sets the value of the insuredAddressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredAddressLine2(String value) {
        this.insuredAddressLine2 = value;
    }

    /**
     * Gets the value of the insuredAddressLine3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredAddressLine3() {
        return insuredAddressLine3;
    }

    /**
     * Sets the value of the insuredAddressLine3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredAddressLine3(String value) {
        this.insuredAddressLine3 = value;
    }

    /**
     * Gets the value of the insuredAddressLine4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredAddressLine4() {
        return insuredAddressLine4;
    }

    /**
     * Sets the value of the insuredAddressLine4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredAddressLine4(String value) {
        this.insuredAddressLine4 = value;
    }

    /**
     * Gets the value of the insuredCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredCity() {
        return insuredCity;
    }

    /**
     * Sets the value of the insuredCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredCity(String value) {
        this.insuredCity = value;
    }

    /**
     * Gets the value of the insuredStateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredStateCode() {
        return insuredStateCode;
    }

    /**
     * Sets the value of the insuredStateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredStateCode(String value) {
        this.insuredStateCode = value;
    }

    /**
     * Gets the value of the insuredZipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredZipCode() {
        return insuredZipCode;
    }

    /**
     * Sets the value of the insuredZipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredZipCode(String value) {
        this.insuredZipCode = value;
    }

    /**
     * Gets the value of the ownerOrganizationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerOrganizationName() {
        return ownerOrganizationName;
    }

    /**
     * Sets the value of the ownerOrganizationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerOrganizationName(String value) {
        this.ownerOrganizationName = value;
    }

    /**
     * Gets the value of the ownerFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerFirstName() {
        return ownerFirstName;
    }

    /**
     * Sets the value of the ownerFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerFirstName(String value) {
        this.ownerFirstName = value;
    }

    /**
     * Gets the value of the ownerMiddleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerMiddleName() {
        return ownerMiddleName;
    }

    /**
     * Sets the value of the ownerMiddleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerMiddleName(String value) {
        this.ownerMiddleName = value;
    }

    /**
     * Gets the value of the ownerLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerLastName() {
        return ownerLastName;
    }

    /**
     * Sets the value of the ownerLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerLastName(String value) {
        this.ownerLastName = value;
    }

    /**
     * Gets the value of the ownerSSN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerSSN() {
        return ownerSSN;
    }

    /**
     * Sets the value of the ownerSSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerSSN(String value) {
        this.ownerSSN = value;
    }

    /**
     * Gets the value of the agentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentNumber() {
        return agentNumber;
    }

    /**
     * Sets the value of the agentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentNumber(String value) {
        this.agentNumber = value;
    }

    /**
     * Gets the value of the agentFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentFirstName() {
        return agentFirstName;
    }

    /**
     * Sets the value of the agentFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentFirstName(String value) {
        this.agentFirstName = value;
    }

    /**
     * Gets the value of the agentLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentLastName() {
        return agentLastName;
    }

    /**
     * Sets the value of the agentLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentLastName(String value) {
        this.agentLastName = value;
    }

}
